$ErrorActionPreference='Continue'
$root='D:\DSH-codex-final-candidate-v2-20260911'; $profile=Join-Path $root 'profiles\web'; $logdir=Join-Path $root 'candidate-4176'
$stdout=Join-Path $logdir 'stdout.log'; $stderr=Join-Path $logdir 'stderr.log'; $result=Join-Path $logdir 'check-result.log'; $dump=Join-Path $logdir 'dump-config.txt'; $model=Join-Path $logdir 'model-catalog-check.txt'
Remove-Item -LiteralPath $stdout,$stderr,$result,$dump,$model -Force -ErrorAction SilentlyContinue
$env:PATH='C:\Program Files\nodejs;C:\Users\Andrew\AppData\Roaming\npm;'+$env:PATH; $env:DSH_HOME=$root; $env:DSH_TELEMETRY_DISABLED='1'; $env:DSH_PERMISSION_MODE='read-only'
foreach($s in @('DEEPSEEK_API_KEY','OPENAI_API_KEY','ANTHROPIC_API_KEY','GOOGLE_API_KEY','POSTMAN_API_KEY')){Remove-Item -LiteralPath ('Env:'+ $s) -ErrorAction SilentlyContinue}
$node='C:\Program Files\nodejs\node.exe'; $entry='C:\Users\Andrew\AppData\Roaming\npm\node_modules\@deepseek-ai\dsh\lib\bin.js'; $proc=$null
try { Push-Location $profile
  & $node $entry --profile web --dump-config *> $dump; Add-Content $result ('DUMP_EXIT='+$LASTEXITCODE)
  $dt=Get-Content -Raw -Encoding UTF8 $dump; $pkg=Get-Content -Raw -Encoding UTF8 (Join-Path $profile 'package.json') | ConvertFrom-Json; $bundles=@($pkg.dsh.profile.bundles)
  Add-Content $result ('PLUGIN_BUNDLES='+$bundles.Count); Add-Content $result ('PLUGIN_BUNDLES_LIST='+($bundles -join ',')); Add-Content $result ('DUMP_HAS_CODEX='+[bool]($dt -match 'dsh-codex-oauth')); Add-Content $result ('DUMP_HAS_AGENT_TEAMS='+[bool]($dt -match 'dsh-agent-teams-nanmicoder-by-andrew'))
  $js='import { builtinModels } from "@earendil-works/pi-ai/providers/all"; const m=builtinModels(); const c=m.getModels("openai-codex"); console.log(JSON.stringify({hasProvider:m.getProviders().includes("openai-codex"),modelCount:c.length,hasGpt6Astra:c.some(x=>x.id==="gpt-6-astra"),models:c.map(x=>x.id).filter(x=>x.includes("astra")||x.includes("gpt-6"))}));'
  $tmp=Join-Path $profile 'model-check.mjs'; Set-Content -LiteralPath $tmp -Value $js -Encoding UTF8; & $node $tmp *> $model; Add-Content $result ('MODEL_CHECK_EXIT='+$LASTEXITCODE); Add-Content $result ('MODEL_OUTPUT='+((Get-Content -Raw -Encoding UTF8 $model) -replace "`r?`n",' ')); Remove-Item -LiteralPath $tmp -Force -ErrorAction SilentlyContinue
  $oauthBin=Join-Path $profile 'node_modules\dsh-codex-oauth\lib\bin.js'; & $node $oauthBin status *> (Join-Path $logdir 'oauth-status.txt'); Add-Content $result ('OAUTH_STATUS_EXIT='+$LASTEXITCODE)
  $proc=Start-Process -FilePath $node -ArgumentList @($entry,'--profile','web','--host','127.0.0.1','--port','4176','--no-open') -WorkingDirectory $profile -WindowStyle Hidden -RedirectStandardOutput $stdout -RedirectStandardError $stderr -PassThru; Add-Content $result ('PID='+$proc.Id)
  $ready=$false; $status=''; for($i=0;$i -lt 30;$i++){Start-Sleep -Seconds 1; if(-not(Get-Process -Id $proc.Id -ErrorAction SilentlyContinue)){break}; try{$resp=Invoke-WebRequest 'http://127.0.0.1:4176/' -UseBasicParsing -TimeoutSec 2;$status=[string]$resp.StatusCode;if($resp.StatusCode -eq 200){$ready=$true;break}}catch{}}
  Add-Content $result ('HTTP_ROOT='+$status); Add-Content $result ('READY='+$ready); Start-Sleep -Seconds 3
  foreach($route in @('/dsh-market/status','/dsh-market/installed','/plugins/dsh-agent-teams-nanmicoder-by-andrew/client.js','/api/dsh-branchline','/api/dsh-restart')){try{$rr=Invoke-WebRequest ('http://127.0.0.1:4176'+$route) -UseBasicParsing -TimeoutSec 5;Add-Content $result ("ROUTE $route STATUS=$($rr.StatusCode)")}catch{$st=if($_.Exception.Response){[int]$_.Exception.Response.StatusCode}else{'ERR'};Add-Content $result ("ROUTE $route STATUS=$st")}}
} finally { if($proc -and (Get-Process -Id $proc.Id -ErrorAction SilentlyContinue)){Stop-Process -Id $proc.Id -Force -ErrorAction SilentlyContinue}; Start-Sleep -Seconds 2; try{$tcp=Get-NetTCPConnection -LocalPort 4176 -State Listen -ErrorAction SilentlyContinue;Add-Content $result ('PORT_FREE='+(-not [bool]$tcp))}catch{Add-Content $result 'PORT_FREE=UNKNOWN'}; Pop-Location }
if(Test-Path $stdout){$sl=Get-Content -Encoding UTF8 $stdout;Add-Content $result ('STDOUT_LINES='+$sl.Count);Add-Content $result ('STDOUT_HAS_ERROR='+[bool]($sl -match 'error|Error|ERROR'))}; if(Test-Path $stderr){$el=Get-Content -Encoding UTF8 $stderr;Add-Content $result ('STDERR_LINES='+$el.Count);Add-Content $result ('STDERR_NONEMPTY='+($el.Count -gt 0));Add-Content $result ('STDERR_TEXT='+($el -join ' | '))}; Get-Content -Raw -Encoding UTF8 $result
