[CmdletBinding()]
param([Parameter(Mandatory=$true)][string]$ReferencePath,[Parameter(Mandatory=$true)][string]$CurrentPath,[string]$OutputPath,[ValidateSet('Json','Txt')][string]$Format='Txt',[switch]$FailOnChanges)
$ErrorActionPreference='Stop'
function Read-Snapshot([string]$p){$x=Get-Content -LiteralPath $p -Raw -Encoding UTF8|ConvertFrom-Json;if($x -is [array]){$e=@($x);$meta=$null}else{$e=@($x.Elements);$meta=$x};return [pscustomobject]@{Elements=$e;Metadata=$meta}}
function Key($e){if($e.RuntimeId){return "rid:$($e.RuntimeId)"};return "fp:$($e.ControlType)|$($e.AutomationId)|$($e.Name)|$($e.ParentRuntimeId)"}
function Map($items){$m=@{};foreach($e in $items){$k=Key $e;if(!$m.ContainsKey($k)){$m[$k]=$e}};return $m}
function Val($v){if($null -eq $v){return $null};if($v -is [array]){return (@($v|ForEach-Object{[string]$_}|Sort-Object)-join ',')};return [string]$v}
$r=Read-Snapshot $ReferencePath;$c=Read-Snapshot $CurrentPath;$rm=Map @($r.Elements);$cm=Map @($c.Elements);$added=New-Object System.Collections.Generic.List[object];$removed=New-Object System.Collections.Generic.List[object];$changed=New-Object System.Collections.Generic.List[object]
foreach($k in $cm.Keys){if(!$rm.ContainsKey($k)){[void]$added.Add($cm[$k])}else{$props=New-Object System.Collections.Generic.List[object];foreach($p in 'Name','ControlType','AutomationId','ParentRuntimeId','ClassName','FrameworkId','ProcessId','IsEnabled','IsOffscreen','IsKeyboardFocusable','HasKeyboardFocus','BoundingRectangle','SupportedPatterns'){if((Val $rm[$k].$p) -cne (Val $cm[$k].$p)){[void]$props.Add([pscustomobject]@{Property=$p;Before=Val $rm[$k].$p;After=Val $cm[$k].$p})}};if($props.Count){[void]$changed.Add([pscustomobject]@{Key=$k;Properties=@($props.ToArray())})}}}
foreach($k in $rm.Keys){if(!$cm.ContainsKey($k)){[void]$removed.Add($rm[$k])}}
$result=[ordered]@{Reference=$ReferencePath;Current=$CurrentPath;Summary=[ordered]@{Added=$added.Count;Removed=$removed.Count;Changed=$changed.Count;Unchanged=$r.Elements.Count-$removed.Count-$changed.Count};Added=@($added.ToArray());Removed=@($removed.ToArray());Changed=@($changed.ToArray())}
if($Format -eq 'Json'){$text=$result|ConvertTo-Json -Depth 10}else{$lines=@("UIA diff",("Added: {0}; Removed: {1}; Changed: {2}; Unchanged: {3}" -f $result.Summary.Added,$result.Summary.Removed,$result.Summary.Changed,$result.Summary.Unchanged));if($added.Count){$lines+='[added]';$lines+=@($added|ForEach-Object{"$($_.Index) $(Key $_) $($_.ControlType) `"$($_.Name)`""})};if($removed.Count){$lines+='[removed]';$lines+=@($removed|ForEach-Object{"$($_.Index) $(Key $_) $($_.ControlType) `"$($_.Name)`""})};if($changed.Count){$lines+='[changed]';foreach($x in $changed){$lines+=$x.Key;foreach($p in $x.Properties){$lines+="  $($p.Property): [$($p.Before)] -> [$($p.After)]"}}};$text=$lines -join "`r`n"}
if($OutputPath){$dir=Split-Path -Parent $OutputPath;if($dir){New-Item -ItemType Directory -Path $dir -Force|Out-Null};Set-Content -LiteralPath $OutputPath -Value $text -Encoding UTF8}else{Write-Output $text};if($FailOnChanges -and ($added.Count+$removed.Count+$changed.Count)){exit 1}
