[CmdletBinding()]
param([string]$Path=(Join-Path $PSScriptRoot 'chatgpt_uia_tree.txt'),[string]$JsonPath=(Join-Path $PSScriptRoot 'chatgpt_uia_tree.json'),[int]$TargetPid=0)
$ErrorActionPreference='Stop';Add-Type -AssemblyName UIAutomationClient;Add-Type -AssemblyName UIAutomationTypes
function Get-RuntimeId($e){try{$v=@($e.GetRuntimeId());if($v.Count){$v -join '.'}}catch{$null}}
function Get-Patterns($e){$map=@{Value=[System.Windows.Automation.ValuePattern];Text=[System.Windows.Automation.TextPattern];Invoke=[System.Windows.Automation.InvokePattern];Scroll=[System.Windows.Automation.ScrollPattern];Selection=[System.Windows.Automation.SelectionPattern];Toggle=[System.Windows.Automation.TogglePattern];ExpandCollapse=[System.Windows.Automation.ExpandCollapsePattern]};$r=New-Object System.Collections.Generic.List[string];foreach($k in $map.Keys){try{$p=$null;if($e.TryGetCurrentPattern($map[$k]::Pattern,[ref]$p)){[void]$r.Add($k)}}catch{}};@($r)}
function Get-TargetWindow{ $root=[System.Windows.Automation.AutomationElement]::RootElement;$cond=New-Object System.Windows.Automation.PropertyCondition([System.Windows.Automation.AutomationElement]::ControlTypeProperty,[System.Windows.Automation.ControlType]::Window);foreach($w in $root.FindAll([System.Windows.Automation.TreeScope]::Children,$cond)){try{$c=$w.Current;$pn=(Get-Process -Id $c.ProcessId -ErrorAction SilentlyContinue).ProcessName;if(($TargetPid -gt 0 -and $c.ProcessId -eq $TargetPid)-or($TargetPid -eq 0-and($pn-match'^(ChatGPT( \(Beta\))?|Codex)$'))){return $w}}catch{}};return $null}
$window=Get-TargetWindow;if(!$window){throw 'ChatGPT/Codex top-level window not found'}
$walker=[System.Windows.Automation.TreeWalker]::RawViewWalker;$items=New-Object System.Collections.Generic.List[object]
$all=@($window.FindAll([System.Windows.Automation.TreeScope]::Descendants,[System.Windows.Automation.Condition]::TrueCondition))
foreach($e in $all){try{$c=$e.Current;$rid=Get-RuntimeId $e;$parent=$walker.GetParent($e);$parentRuntimeId=if($parent){Get-RuntimeId $parent}else{$null};$depth=1;$guard=0;while($parent -and $guard -lt 80){$depth++;$parent=$walker.GetParent($parent);$guard++};$r=$c.BoundingRectangle;$o=[pscustomobject]@{Index=$items.Count;Depth=$depth;RuntimeId=$rid;ParentRuntimeId=$parentRuntimeId;Name=[string]$c.Name;AutomationId=[string]$c.AutomationId;ControlType=$c.ControlType.ProgrammaticName;ClassName=[string]$c.ClassName;FrameworkId=[string]$c.FrameworkId;ProcessId=$c.ProcessId;IsEnabled=$c.IsEnabled;IsOffscreen=$c.IsOffscreen;IsKeyboardFocusable=$c.IsKeyboardFocusable;HasKeyboardFocus=$c.HasKeyboardFocus;BoundingRectangle=[string]::Format('[{0},{1},{2},{3}]',$r.X,$r.Y,$r.Width,$r.Height);SupportedPatterns=@(Get-Patterns $e)};[void]$items.Add($o)}catch{Write-Verbose ("skip: $($_.Exception.Message)")}}
foreach($p in @($Path,$JsonPath)){ $d=Split-Path -Parent $p;if($d){New-Item -ItemType Directory -Path $d -Force|Out-Null} }
$meta=[ordered]@{SchemaVersion=2;CapturedAtUtc=(Get-Date).ToUniversalTime().ToString('o');ProcessId=$window.Current.ProcessId;WindowName=$window.Current.Name;WindowRuntimeId=Get-RuntimeId $window;Walker='RawViewWalker';ElementCount=$items.Count;Elements=@($items.ToArray())}
$meta|ConvertTo-Json -Depth 10|Set-Content -LiteralPath $JsonPath -Encoding UTF8
$lines=New-Object System.Collections.Generic.List[string];[void]$lines.Add("UIA dump $($meta.CapturedAtUtc) PID=$($meta.ProcessId) WindowRuntimeId=$($meta.WindowRuntimeId)");foreach($x in $items.ToArray()){[void]$lines.Add(('{0}{1}: RuntimeId="{2}" ParentRuntimeId="{3}" Name="{4}" AutomationId="{5}" ControlType={6} Class="{7}" Framework="{8}" PID={9} Enabled={10} Offscreen={11} Focusable={12} Focus={13} Rect={14} Patterns={15}'-f('  '*$x.Depth),$x.Index,$x.RuntimeId,$x.ParentRuntimeId,([string]$x.Name).Replace('"','''"'),$x.AutomationId,$x.ControlType,$x.ClassName,$x.FrameworkId,$x.ProcessId,$x.IsEnabled,$x.IsOffscreen,$x.IsKeyboardFocusable,$x.HasKeyboardFocus,$x.BoundingRectangle,($x.SupportedPatterns-join',')))};$lines|Set-Content -LiteralPath $Path -Encoding UTF8;Write-Output "Wrote $($items.Count) elements for PID $($window.Current.ProcessId)"
